### ISSUE TITLE
Support for VS 2019

### ISSUE THREAD

**Issue by ite-jankl** [jsakamoto/xUnitTestProjectTemplate#2]
Adding support for VS2019 would be great.

Is there anything standing in its way? Anything that actually has to change/be implemented? Or is it just a metadata update to indicate support?

**Comment by jsakamoto** [comment]
I would be needed not only update metadata but also change some implementations such as update NuGet package references.

I think, there is no need for the xUnit test project template for ".NET Framework" today (and, VS2019 provides xUnit test project template for ".NET Core").

![image](https://user-images.githubusercontent.com/95908/73498174-df484b80-43ff-11ea-9100-002259696660.png)

However, if you need, I'll consider to add VS2019 support to this project template.

**Comment by ite-jankl** [comment]
> I think, there is no need for the xUnit test project template for ".NET Framework" today

What makes you think so? Because .NET core is the tech for new (non winforms) projects?

I am creating xUnit test projects for .NET Framework. At the moment I create an mstest project and manually replace csproj and packages content, and was checking for alternatives to doing it/this much manually.

**Comment by jsakamoto** [comment]
>What makes you think so? 

Sorry, my wording was not accurate. I just wan to say the needs of xUnit project template for .NET Framework will be shrink in the future, especially when after .NET 5 came true.

Anyway, I'm not to be against your suggestion.

Therefore, I spent a few days to update this project.

However, I could not complete this work, because xUnit Test project for VS2019 had been more complex than old versions.

I was already migrated .NET Core base production, therefore, I feel this work is not worth it for myself.

I also have to do other OSS works, so please let me put off the resolving this issue.

**Comment by ite-jankl** [comment]
No problem, thank you very much for your effort. :)

**Comment by jsakamoto** [comment]
Today, I finally, completed the work for support VS2019.

Please try it out. :)

- https://marketplace.visualstudio.com/items?itemName=jsakamoto.xUnitTestProjectTemplate

**Comment by ite-jankl** [comment]
Oh, very unexpected to me. Thank you very much! :)

I installed it, and can confirm it works to create a new project. A nuget dependency seems to be missing for Xunit and Fact, but when I will use it I will have to adjust stuff on the new project anyway.

Nevertheless next time I create a test project this will be very useful to me. Thank you very much! For the fast response and implementation as well!
